server:
  port: 8090
logging:
  level:
    root: info
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:enjoy@eureka1:7001/eureka,http://admin:enjoy@eureka2:7002/eureka,http://admin:enjoy@eureka3:7003/eureka

SPRINGCLOUD-PROVIDER-PRODUCT:
  ribbon:
    listOfServers: http://localhost:8080,http://localhost:8082,http://localhost:8083
